AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS MyAwsApiGraalNativeImage API - my.aws.api.graal.native.image::my-aws-api-graal-native-image
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyAwsApiGraalNativeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.aws.api.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/my-aws-api-graal-native-image-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyAwsApiGraalNativeImageApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyAwsApiGraalNativeImageApi
